#pragma once
#include "core/math_tools.h"
#include "core/control.h"
#include "core/filter.h"
#include "core/math_tools.h"
#include "core/oscillator.h"
#include "core/units.h"
#include "core/linear_predictive_coding.h"
// #include "core/experimental.h"

#include "shell/control.h"
#include "shell/dsp_graph.h"
#include "shell/filter.h"
#include "shell/math_functions.h"
#include "shell/oscillator.h"
#include "shell/units.h"